;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Setpoints]
Pos=194,52
Size=142,133
Collapsed=0

[Window][PID Tuning]
Pos=1228,86
Size=127,109
Collapsed=0

[Docking][Data]


;;;<<<Layout_655921752_Default>>>;;;

;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker

;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
